package Nakumatt.dao;
// Generated Oct 16, 2013 2:10:04 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Creditcards generated by hbm2java
 */
public class Creditcards  implements java.io.Serializable {


     private Integer creditcardId;
     private Orders orders;
     private String type;
     private Date expirationDate;
     private int cardSecurityCod;
     private float orderAmount;
     private boolean active;

    public Creditcards() {
    }

    public Creditcards(Orders orders, String type, Date expirationDate, int cardSecurityCod, float orderAmount, boolean active) {
       this.orders = orders;
       this.type = type;
       this.expirationDate = expirationDate;
       this.cardSecurityCod = cardSecurityCod;
       this.orderAmount = orderAmount;
       this.active = active;
    }
   
    public Integer getCreditcardId() {
        return this.creditcardId;
    }
    
    public void setCreditcardId(Integer creditcardId) {
        this.creditcardId = creditcardId;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }
    public int getCardSecurityCod() {
        return this.cardSecurityCod;
    }
    
    public void setCardSecurityCod(int cardSecurityCod) {
        this.cardSecurityCod = cardSecurityCod;
    }
    public float getOrderAmount() {
        return this.orderAmount;
    }
    
    public void setOrderAmount(float orderAmount) {
        this.orderAmount = orderAmount;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }




}


