package Nakumatt.dao;
// Generated Oct 10, 2013 1:47:08 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer orderId;
     private Shipper shipper;
     private Carts carts;
     private Date orderDate;
     private Date requeredDate;
     private Date shippingDate;
     private int quantity;
     private float orderAmount;
     private boolean active;
     private Set creditcardses = new HashSet(0);

    public Orders() {
    }

	
    public Orders(Shipper shipper, Carts carts, Date orderDate, Date requeredDate, Date shippingDate, int quantity, float orderAmount, boolean active) {
        this.shipper = shipper;
        this.carts = carts;
        this.orderDate = orderDate;
        this.requeredDate = requeredDate;
        this.shippingDate = shippingDate;
        this.quantity = quantity;
        this.orderAmount = orderAmount;
        this.active = active;
    }
    public Orders(Shipper shipper, Carts carts, Date orderDate, Date requeredDate, Date shippingDate, int quantity, float orderAmount, boolean active, Set creditcardses) {
       this.shipper = shipper;
       this.carts = carts;
       this.orderDate = orderDate;
       this.requeredDate = requeredDate;
       this.shippingDate = shippingDate;
       this.quantity = quantity;
       this.orderAmount = orderAmount;
       this.active = active;
       this.creditcardses = creditcardses;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Shipper getShipper() {
        return this.shipper;
    }
    
    public void setShipper(Shipper shipper) {
        this.shipper = shipper;
    }
    public Carts getCarts() {
        return this.carts;
    }
    
    public void setCarts(Carts carts) {
        this.carts = carts;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getRequeredDate() {
        return this.requeredDate;
    }
    
    public void setRequeredDate(Date requeredDate) {
        this.requeredDate = requeredDate;
    }
    public Date getShippingDate() {
        return this.shippingDate;
    }
    
    public void setShippingDate(Date shippingDate) {
        this.shippingDate = shippingDate;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public float getOrderAmount() {
        return this.orderAmount;
    }
    
    public void setOrderAmount(float orderAmount) {
        this.orderAmount = orderAmount;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set getCreditcardses() {
        return this.creditcardses;
    }
    
    public void setCreditcardses(Set creditcardses) {
        this.creditcardses = creditcardses;
    }




}


