package Nakumatt.dao;
// Generated Oct 16, 2013 2:10:04 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer productId;
     private Categories categories;
     private String name;
     private float price;
     private String description;
     private boolean active;
     private Set cartses = new HashSet(0);
     private Set offerses = new HashSet(0);

    public Products() {
    }

	
    public Products(Categories categories, String name, float price, String description, boolean active) {
        this.categories = categories;
        this.name = name;
        this.price = price;
        this.description = description;
        this.active = active;
    }
    public Products(Categories categories, String name, float price, String description, boolean active, Set cartses, Set offerses) {
       this.categories = categories;
       this.name = name;
       this.price = price;
       this.description = description;
       this.active = active;
       this.cartses = cartses;
       this.offerses = offerses;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set getCartses() {
        return this.cartses;
    }
    
    public void setCartses(Set cartses) {
        this.cartses = cartses;
    }
    public Set getOfferses() {
        return this.offerses;
    }
    
    public void setOfferses(Set offerses) {
        this.offerses = offerses;
    }




}


