package Nakumatt.dao;
// Generated Oct 16, 2013 2:10:04 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String password;
     private String fname;
     private String lname;
     private String address;
     private String shippingAddress;
     private String city;
     private String contactno;
     private String emailaddress;
     private String typeId;
     private String idNo;
     private boolean active;
     private Set cartses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String password, String fname, String lname, String address, String shippingAddress, String city, String contactno, String emailaddress, String typeId, String idNo, boolean active) {
        this.username = username;
        this.password = password;
        this.fname = fname;
        this.lname = lname;
        this.address = address;
        this.shippingAddress = shippingAddress;
        this.city = city;
        this.contactno = contactno;
        this.emailaddress = emailaddress;
        this.typeId = typeId;
        this.idNo = idNo;
        this.active = active;
    }
    public Users(String username, String password, String fname, String lname, String address, String shippingAddress, String city, String contactno, String emailaddress, String typeId, String idNo, boolean active, Set cartses) {
       this.username = username;
       this.password = password;
       this.fname = fname;
       this.lname = lname;
       this.address = address;
       this.shippingAddress = shippingAddress;
       this.city = city;
       this.contactno = contactno;
       this.emailaddress = emailaddress;
       this.typeId = typeId;
       this.idNo = idNo;
       this.active = active;
       this.cartses = cartses;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getShippingAddress() {
        return this.shippingAddress;
    }
    
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getContactno() {
        return this.contactno;
    }
    
    public void setContactno(String contactno) {
        this.contactno = contactno;
    }
    public String getEmailaddress() {
        return this.emailaddress;
    }
    
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }
    public String getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }
    public String getIdNo() {
        return this.idNo;
    }
    
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set getCartses() {
        return this.cartses;
    }
    
    public void setCartses(Set cartses) {
        this.cartses = cartses;
    }




}


